### ISSUE TITLE
Fedora 36 - Today's package updates removed your obs packages

### ISSUE THREAD

**Issue by tomtomhotep** [mihawk90/obs-studio.spec#6]
sudo dnf install obs-studio-libs-28.1.2-11.fc36.x86_64.rpm
Last metadata expiration check: 0:16:14 ago on Sat 26 Nov 2022 07:24:33 AM EST.
Error: 
 Problem: conflicting requests
  - nothing provides qt5-qtbase(x86-64) = 5.15.6 needed by obs-studio-libs-28.1.2-11.fc36.x86_64

** Today's update installed qt5-qtbase 5.15.7

Please help!  I stream this Wednesday!

Thank You.

**Comment by mihawk90** [comment]
Goddamn qt-updates... I'll recompile

**Comment by mihawk90** [comment]
https://github.com/mihawk90/obs-studio.spec/releases/tag/v28.1.2-12
